language: node_js
dist: trusty
sudo: required
node_js: stable

env:
  matrix:
  - PATH=$HOME:$HOME/purescript:$PATH

install:
- PURS_VER=v0.13.5
- SPAGO_VER=0.10.0.0
- wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$PURS_VER/linux64.tar.gz
- wget -O $HOME/spago.tar.gz https://github.com/spacchetti/spago/releases/download/$SPAGO_VER/linux.tar.gz
- tar -xvf $HOME/purescript.tar.gz -C $HOME/
- tar -xvf $HOME/spago.tar.gz -C $HOME/
- chmod a+x $HOME/purescript/purs
- chmod a+x $HOME/spago
- spago install

script:
- export VERSION=branch-job-$TRAVIS_JOB_NUMBER
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then export VERSION=pull-request-job-$TRAVIS_JOB_NUMBER;
  fi
- if [[ "$TRAVIS_TAG" != "" ]]; then export VERSION=$TRAVIS_TAG; fi
- spago build
- spago test
